{{- if and $.Values.processExporter $.Values.processExporter.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iap-process-exporter
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "podmonitor"
  annotations:
    kubernetes.io/description: "Itential Automation Platform Pod Monitor."
    {{- include "iap.annotations" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: process-metrics
      relabelings:
        - action: keep
          regex: ([\d\.]+):{{ $.Values.processExporter.port | default 9256 }}
          sourceLabels: [ __address__ ]
        - action: labeldrop
          regex: __meta_kubernetes_service_annotation_kubectl_kubernetes_io_last_applied_configuration
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames: [ {{ .Release.namespace }} ]
  selector:
    matchLabels:
      app.kubernetes.io/name: iap
{{- end -}}
{{- if and .Values.mongoqueryExporter .Values.mongoqueryExporter.enabled .Values.mongoqueryExporter.podMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "iap.fullname" . }}-mongodb-query-exporter
  {{- if .Values.mongoqueryExporter.podMonitor.namespace }}
  namespace: {{ .Values.mongoqueryExporter.podMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "mongodb-query-exporter"
spec:
  selector:
    matchLabels:
      {{- include "iap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "mongodb-query-exporter"
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    {{- if .Values.mongoqueryExporter.podMonitor.interval }}
    interval: {{ .Values.mongoqueryExporter.podMonitor.interval }}
    {{- end }}
    {{- if .Values.mongoqueryExporter.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.mongoqueryExporter.podMonitor.scrapeTimeout }}
    {{- end }}
{{- end -}}