{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iap.labels" . | nindent 4 }}
  annotations:
    {{- include "iap.annotations" . | nindent 4 }}
    {{- if .Values.serviceAccount.aws.elasticache.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.aws.elasticache.roleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}